import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";
import {Toaster} from "react-hot-toast";

const outfit = Outfit({
  variable: "--font-outfit",
  subsets: ["latin", "latin-ext"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    return (
        <html lang="es" className="h-full min-h-screen">
        <body className={`${outfit.variable} antialiased`}>
            {children}
            <Toaster position="top-right" />
        </body>
        </html>
    );
}
